export default {
  "login": "Som-Nang",
  "id": 59254471,
  "node_id": "MDQ6VXNlcjU5MjU0NDcx",
  "avatar_url": "https://avatars2.githubusercontent.com/u/59254471?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Som-Nang",
  "html_url": "https://github.com/Som-Nang",
  "followers_url": "https://api.github.com/users/Som-Nang/followers",
  "following_url": "https://api.github.com/users/Som-Nang/following{/other_user}",
  "gists_url": "https://api.github.com/users/Som-Nang/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Som-Nang/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Som-Nang/subscriptions",
  "organizations_url": "https://api.github.com/users/Som-Nang/orgs",
  "repos_url": "https://api.github.com/users/Som-Nang/repos",
  "events_url": "https://api.github.com/users/Som-Nang/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Som-Nang/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Som Nang",
  "company": 'DEvGravity',
  "blog": "somnangportfolio.netlify.app",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": '> New Generation of Developer <',
  "twitter_username": 'somnang',
  "public_repos": 10,
  "public_gists": 2,
  "followers": 36510,
  "following": 348,
  "created_at": "2019-12-26T12:29:58Z",
  "updated_at": "2020-09-24T06:16:30Z"
};
